function formatBytes(bytes) {
  if (!bytes || bytes <= 0) return "Unknown";
  const units = ["B", "KB", "MB", "GB"];
  let value = bytes;
  let index = 0;

  while (value >= 1024 && index < units.length - 1) {
    value /= 1024;
    index += 1;
  }

  return `${value.toFixed(2)} ${units[index]}`;
}

function formatPrice(price) {
  if (price === null || price === undefined || Number.isNaN(Number(price))) {
    return "N/A";
  }

  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(Number(price));
}

function mediaTypeLabel(mimeType) {
  if (mimeType.startsWith("image/")) return "Image";
  if (mimeType.startsWith("video/")) return "Video";
  return "File";
}

export function generatePropertyReadme(property) {
  const lines = [];
  const now = new Date();
  const images = property.mediaFiles.filter((file) => file.mimeType.startsWith("image/"));
  const videos = property.mediaFiles.filter((file) => file.mimeType.startsWith("video/"));
  const others = property.mediaFiles.filter(
    (file) => !file.mimeType.startsWith("image/") && !file.mimeType.startsWith("video/")
  );
  const totalBytes = property.mediaFiles.reduce((sum, file) => sum + (file.sizeBytes || 0), 0);
  const typeTotals = property.mediaFiles.reduce(
    (acc, file) => {
      const key = mediaTypeLabel(file.mimeType);
      acc[key].count += 1;
      acc[key].bytes += file.sizeBytes || 0;
      return acc;
    },
    {
      Image: { count: 0, bytes: 0 },
      Video: { count: 0, bytes: 0 },
      File: { count: 0, bytes: 0 },
    }
  );

  lines.push(`# ${property.title}`);
  lines.push("");
  lines.push("### Property Media Portfolio");
  lines.push("");
  lines.push("_A clean summary of imported images and videos for this property._");
  lines.push("");
  lines.push("## Quick Snapshot");
  lines.push("");
  lines.push(`- **Property:** ${property.title}`);
  lines.push(`- **Location:** ${property.location || "N/A"}`);
  lines.push(`- **Price:** ${formatPrice(property.price)}`);
  lines.push(`- **Description:** ${property.description || "N/A"}`);
  lines.push(`- **Report Date:** ${now.toLocaleString()}`);
  lines.push("");
  lines.push("## Media Overview");
  lines.push("");
  lines.push("| Category | Count | Total Size |");
  lines.push("| --- | ---: | ---: |");
  lines.push(`| Total Media | ${property.mediaFiles.length} | ${formatBytes(totalBytes)} |`);
  lines.push(`| Images | ${images.length} | ${formatBytes(typeTotals.Image.bytes)} |`);
  lines.push(`| Videos | ${videos.length} | ${formatBytes(typeTotals.Video.bytes)} |`);
  lines.push(`| Other | ${others.length} | ${formatBytes(typeTotals.File.bytes)} |`);
  lines.push("");

  if (!property.mediaFiles.length) {
    lines.push("No media files were found for this property.");
    return lines.join("\n");
  }

  lines.push("## Media Files");
  lines.push("");
  lines.push("### Images");
  lines.push("");
  if (!images.length) {
    lines.push("No image files available.");
  } else {
    lines.push("| # | File Name | MIME Type | Size |");
    lines.push("| ---: | --- | --- | ---: |");
    images.forEach((file, index) => {
      lines.push(`| ${index + 1} | ${file.name} | ${file.mimeType} | ${formatBytes(file.sizeBytes || 0)} |`);
    });
  }
  lines.push("");
  lines.push("### Videos");
  lines.push("");
  if (!videos.length) {
    lines.push("No video files available.");
  } else {
    lines.push("| # | File Name | MIME Type | Size |");
    lines.push("| ---: | --- | --- | ---: |");
    videos.forEach((file, index) => {
      lines.push(`| ${index + 1} | ${file.name} | ${file.mimeType} | ${formatBytes(file.sizeBytes || 0)} |`);
    });
  }
  lines.push("");
  if (others.length) {
    lines.push("### Other Files");
    lines.push("");
    lines.push("| # | File Name | MIME Type | Size |");
    lines.push("| ---: | --- | --- | ---: |");
    others.forEach((file, index) => {
      lines.push(`| ${index + 1} | ${file.name} | ${file.mimeType} | ${formatBytes(file.sizeBytes || 0)} |`);
    });
    lines.push("");
  }

  lines.push("> End of media report.");
  lines.push("---");
  lines.push("Generated by Property Listing Manager");

  return lines.join("\n");
}
